# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myreferal', models.CharField(blank=True, max_length=7, null=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('referalcode', models.CharField(blank=True, max_length=7, unique=True)),
                ('referalany', models.CharField(blank=True, max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='referal',
            name='referal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Register'),
        ),
    ]
